export const REGION_LIST = [
    { title: "서울", full: "서울특별시" },
    { title: "부산", full: "부산광역시" },
    { title: "대구", full: "대구광역시" },
    { title: "인천", full: "인천광역시" },
    { title: "광주", full: "광주광역시" },
    { title: "대전", full: "대전광역시" },
    { title: "울산", full: "울산광역시" },
    { title: "세종", full: "세종특별자치시" },
    { title: "강원", full: "강원도" },
    { title: "경기", full: "경기도" },
    { title: "경남", full: "경상남도" },
    { title: "경북", full: "경상북도" },
    { title: "전남", full: "전라남도" },
    { title: "전북", full: "전라북도" },
    { title: "제주", full: "제주특별자치도" },
    { title: "충남", full: "충청남도" },
    { title: "충북", full: "충청북도" },
    { title: "해외", full: "해외" }
];
