export const GLOBAL_SESSION_ACCESS_PAGE = "GLOBAL/SESSION_ACCESS_PAGE";
export const GLOBAL_SESSION_NOT_ACCESS_PAGE = "GLOBAL/SESSION_NOT_ACCESS_PAGE";

// Session Event
export const GLOBAL_SESSION_SAVE = "GLOBAL/SESSION_SAVE";
export const GLOBAL_SESSION_UPDATE = "GLOBAL/SESSION_UPDATE";
export const GLOBAL_SESSION_REMOVE = "GLOBAL/SESSION_REMOVE";

// Message Event
export const GLOBAL_MESSAGE_SAVE = "GLOBAL/MESSAGE_SAVE";
export const GLOBAL_MESSAGE_ADD = "GLOBAL/MESSAGE_ADD";
export const GLOBAL_MESSAGE_CLEAR = "GLOBAL/MESSAGE_CLEAR";

// UI Event
export const GLOBAL_LEFT_SIDEBAR_SHOW = "GLOBAL/LEFT_SIDEBAR_SHOW";
export const GLOBAL_LEFT_SIDEBAR_HIDE = "GLOBAL/LEFT_SIDEBAR_HIDE";
export const GLOBAL_SEARCH_SIDEBAR_SHOW = "GLOBAL/SEARCH_SIDEBAR_SHOW";
export const GLOBAL_SEARCH_SIDEBAR_HIDE = "GLOBAL/SEARCH_SIDEBAR_HIDE";
export const GLOBAL_BREADCRUMB = "GLOBAL/GLOBAL_BREADCRUMB";

export const GLOBAL_SEARCH_TAG_UPDATE = "GLOBAL/GLOBAL_SEARCH_TAG_UPDATE";
export const GLOBAL_SEARCH_TAG_DELETE = "GLOBAL/GLOBAL_SEARCH_TAG_DELETE";
export const GLOBAL_SEARCH_TAB = "GLOBAL/GLOBAL_SEARCH_TAB";
