import * as VIRTUAL_ESTIMATE_PROPERTYS from "shared/constant/virtual_estimate_property.const";

export const PROPERTYS = VIRTUAL_ESTIMATE_PROPERTYS.PROPERTYS;
export const SHOT_KIND_PROPERTY = VIRTUAL_ESTIMATE_PROPERTYS.SHOT_KIND_PROPERTY;
export const SIZE_PROPERTY = VIRTUAL_ESTIMATE_PROPERTYS.SIZE_PROPERTY;
export const MATERIAL_PROPERTY = VIRTUAL_ESTIMATE_PROPERTYS.MATERIAL_PROPERTY;
export const DIRECTING_PROPERTY = VIRTUAL_ESTIMATE_PROPERTYS.DIRECTING_PROPERTY;
export const PROXY_DIRECTING_PROPERTY = VIRTUAL_ESTIMATE_PROPERTYS.PROXY_DIRECTING_PROPERTY;
export const PLACE_PROPERTY = VIRTUAL_ESTIMATE_PROPERTYS.PLACE_PROPERTY;
export const HAS_PROPERTY = VIRTUAL_ESTIMATE_PROPERTYS.HAS_PROPERTY;
export const NUKKI_KIND_PROPERTY = VIRTUAL_ESTIMATE_PROPERTYS.NUKKI_KIND_PROPERTY;

export const UNIT_DATA = {
    CUT: { CODE: "CUT", NAME: "컷" },
    COUNT: { CODE: "COUNT", NAME: "개" },
    CONCEPT: { CODE: "CONCEPT", NAME: "컨셉" },
    PERSON: { CODE: "PERSON", NAME: "명" },
    TIME: { CODE: "TIME", NAME: "시간" }
};

export const PRE_TEXT = {
    CUT: { CODE: "CUT", NAME: "필요컷 수" },
    COUNT: { CODE: "COUNT", NAME: "제품 수" },
    CONCEPT: { CODE: "CONCEPT", NAME: "컨셉 수" },
    TOTAL: { CODE: "TOTAL", NAME: "총" }
    // TIME: { CODE: "TIME", NAME: "시간" }
};

export const STEP_KEY = {
    FIRST: "FIRST",
    SECOND: "SECOND",
    THIRD: "THIRD"
};

